node_env = "development"

[api]
url = "https://bangloan-defi-api-ci.fly.dev"

[app]
url = "http://127.0.0.1:3000"

[services.supabase]
url = "https://iucsqvvjujqcncowypnr.supabase.co"

[services.ethers]
# settings for baseSepolia, see others: https://chainlist.org/
url = "https://sepolia.base.org"
wss = "https://sepolia.base.org"

[evm.address]
# bangloan-devops wallets.  wallet numbers are 1-based (as opposed to 0-based in anvil)
# devops admin/owner (wallet 1) - public address, okay to share
owner = "0xC54f8862C4bB1c114d5b6C666410eb242a6c97Db"
# devops operator (wallet 2) - public address, okay to share
operator = "0xC54f8862C4bB1c114d5b6C666410eb242a6c97Db"

# devops custodian (wallet 3) - public address, okay to share
custodian = "0xC54f8862C4bB1c114d5b6C666410eb242a6c97Db"
# devops operator (wallet 4) - public address, okay to share
treasury = "0xC54f8862C4bB1c114d5b6C666410eb242a6c97Db"
# devops operator (wallet 5) - public address, okay to share
activity_reward = "0xC54f8862C4bB1c114d5b6C666410eb242a6c97Db"

[users]
# Associated with devops admin/owner (wallet 1)
admin.email_address = "test+admin@bangloan.io"
# Associated with devops alice (wallet 6)
alice.email_address = "test+alice@bangloan.io"
# Associated with devops bob (wallet 7)
bob.email_address = "test+bob@bangloan.io"

[operation.createVault]
collateral_percentage = 300
